processors:
  filter/network-connections:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - system.network.connections
  attributes/add-location:
    actions:
      - key: location
        action: insert
        value: europe
  span/rename:
    name:
      from_attributes: [location, item, quantity]
      separator: ":"
  batch:
    timeout: 10s

receivers:
  hostmetrics:
    collection_intervals: 10s
    scrapers:
      memory:
      network:
        include:
          match_type: strict
          interfaces: [eth0]

  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes/add-location, span/rename]
      exporters: [logging]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch, filter/network-connections]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
